Repository kadda002/CS-100-Final-Project, pull requests merged in 2020-07, with the labels that each got.

#5 Decorator pattern input
  main.cpp
  order.hpp
  toppings/add_top.hpp
  toppings/toppings_decorator.hpp
  toppings/toppings_tests.hpp
Labels: bug

#6 decorator pattern input testing
  main.cpp
  order.hpp
  toppings/add_top.hpp
  toppings/anchovy.hpp
  toppings/bellpepper.hpp
  toppings/chicken.hpp
  toppings/meatball.hpp
  toppings/mushroom.hpp
  toppings/olive.hpp
  toppings/onion.hpp
  toppings/pepperoni.hpp
  toppings/salami.hpp
  toppings/spinach.hpp
  toppings/tomato.hpp
  toppings/toppings_tests.hpp
  toppings/tuna.hpp
Labels: help wanted

#9 Zachattack98/new decorator pattern
  main_pizza_decorator.hpp
  pizza_decorator.hpp
  toppings/anchovy.hpp
  toppings/bellpepper.hpp
  toppings/chicken.hpp
  toppings/meatball.hpp
  toppings/mushroom.hpp
  toppings/olive.hpp
  toppings/onion.hpp
  toppings/pepperoni.hpp
  toppings/salami.hpp
  toppings/spinach.hpp
  toppings/tomato.hpp
  toppings/toppings_decorator.hpp
  toppings/toppings_tests.hpp
  toppings/tuna.hpp
  toppings_list.hpp
  unit_test.cpp
Labels: documentation

#14 Modified the factory output so that everything has a base class of pizza
  Italian_style.hpp
  base_pizza.hpp
  basic_pizza.hpp
  main_pizza_factory.cpp
  pizza.hpp
  pizza_factory.hpp
Labels: enhancement

#12 Zachattack98/combine patterns
  base_pizza.hpp
  combined_unit_tests.hpp
  main_pizza.cpp
  pizza_decorator.hpp
  pizza_design.hpp
  toppings/anchovy.hpp
  toppings/bellpepper.hpp
  toppings/chicken.hpp
  toppings/meatball.hpp
  toppings/mushroom.hpp
  toppings/olive.hpp
  toppings/onion.hpp
  toppings/pepperoni.hpp
  toppings/salami.hpp
  toppings/spinach.hpp
  toppings/tomato.hpp
  toppings/toppings_decorator.hpp
  toppings/toppings_tests.hpp
  toppings/tuna.hpp
  unit_test.cpp
Labels: documentation
